services:
  mysql:
    image: mysql:8.0.27
    container_name: mysql-container
    networks:
      - art-cart-network
    environment:
      MYSQL_DATABASE: artcartdb
      MYSQL_USER: manash
      MYSQL_PASSWORD: manash
      MYSQL_ROOT_PASSWORD: root

    ports:
      - "3307:3306"

  artcart-backend:
    image: manash/artcart-backend
    container_name: art-cart-container
    restart: always
    networks:
      - art-cart-network
    environment:
      PROFILE: prod
      MYSQL_HOST: mysql-container
      DATABASE_NAME: artcartdb
      MYSQL_USERNAME: manash
      MYSQL_PASSWORD: manash
    ports:
      - "9090:9090"
    depends_on:
      - mysql
  artcart-front-end:
    image: manash/artcart-frontend
    container_name: art-cart-frontend
    depends_on:
      - artcart-backend
    ports:
      - "8080:80"

volumes:
  artcartvolume:
networks:
  art-cart-network:
    driver: bridge