server:
  port: 9090
spring:
  datasource:
    url: jdbc:mysql://${MYURL}:11822/defaultdb
    username: ${MY_USERNAME}
    password: ${MY_SERVICE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
